### PR TITLE
Add support for ST_MakeValid

### PR DESCRIPTION
**Pull request by victorquinn**
Hi, thanks for your library, it's very useful for working with PostGIS!

We use this extensively in our stack, may be submitting more PRs shortly. Currently for the things your library doesn't support we fall back to `knex.raw` but it would be great to be able to use your library for all our PostGIS queries without falling back like that!

### CODE REVIEW

**Comment by jfgodoy** [comment]
Hi @victorquinn, thank you for contributing.
please, add the new function to the README

**Comment by victorquinn** [comment]
Oops good call, sorry I missed that, done!

**Comment by jfgodoy** [comment]
published on npm as knex-postgis@0.1.9
:)

**Comment by victorquinn** [comment]
Thanks for the quick turnaround!!

**Pull request merged**
