### PR TITLE
Add support for ST_Within, ST_DWithin

### PR DESCRIPTION
**Pull request by victorquinn**

### CODE REVIEW

**Comment by jfgodoy** [comment]
Hi @victorquinn!
The `st_within` and `st_Dwithin` functions expect a geometry in their two first parameters, so use `formatter.wrapWKT` to properly scape.
thank you for your continuos collaboration :+1:

**Comment by victorquinn** [comment]
I went back and forth on it and thought this was proper but that makes sense, I'll make the change!

**Comment by jfgodoy** [comment]
good!
I discovered an issue in your wrapBoolean function which also affects the wrapNumber function. If the input value is a string then it should be returned wrapped so it's interpreted as a column name.

**Comment by victorquinn** [comment]
Ahh very good catch there, I'll update it accordingly!

**Comment by jfgodoy** [comment]
This test is wrong 
```
    it('works with a column name as the distance', function() {
      console.log(queryBuilder().select(st.dwithin('a', 'b', 'distanceColumn')).toString())
      testsql(queryBuilder().select(st.dwithin('a', 'b', 'distanceColumn')), {
        sql: 'select ST_DWithin("a", "b", ?)',
        bindings: ['distanceColumn']
      });
    });
```
In this case `distanceColumn` is treated as a literal
``` 
console.log(queryBuilder().select(st.dwithin('a', 'b', 'distanceColumn')).toString())
// will print: select ST_DWithin("a", "b", 'distanceColumn')
```
instead of returning `value` from the `wrapBoolean` and `wrapNumber` functions, you must return `knex.raw(this.wrap(value), [])` to do the trick.

Also, you don't need lodash to do a simple `typeof value === 'string'`

**Comment by victorquinn** [comment]
Ok, these issues should both be resolved now!

**Comment by jfgodoy** [comment]
:+1: 
thank you!!

**Comment by jfgodoy** [comment]
I merged this pull request from command line, I don't know why this appears closed instead of merged

**Comment by victorquinn** [comment]
Whoops, meant to add Distance as a separate PR but it went in here for some reason and re-opened, probably related to the command line merge, sorry

**Comment by jfgodoy** [comment]
ok, no problem.
I will close this PR. Please open a new one with the new commits.

**Pull request closed without merging**
