### PR TITLE
add basic support for typescript

### PR DESCRIPTION
**Pull request by jfgodoy**
add type definitions for typescript

### CODE REVIEW

**Comment by ctusch** [comment]
I tested it and it looks good and seems to work except one thing: The TypeScript compiler will throw an error because in your definition you are importing types from the package `geojson` which is not a dependency you've added. The original `@types/knex-postgis` package has it in its `package.json`:
```
"dependencies": {
  "@types/geojson": "*",
  "knex": "^0.16.1"
},
```
I guess only the type definitions are needed because you only want to define the shape of the object and not attach any functions to it.

(Strangely the pushed package.json on GitHub only has the `knex` dependency. But when you install it via npm you get both.)

If I remember correctly it's important to add it to `dependencies` and not `devDependencies` because those won't be installed when someone installs your package via npm.

**Comment by jfgodoy** [comment]
thank you @ctusch for the review. Now I just fixed the issue with geojson.
can you try now?

**Comment by ctusch** [comment]
Everything seems to work fine now!

**Comment by jfgodoy** [comment]
thank you @ctusch!! 
I published this change to npm as v0.10.0

**Comment by ctusch** [comment]
Thank you too! :)

**Pull request merged**
